Sys.getlocale()
Sys.setlocale("LC_ALL", "C")
Sys.setlocale("LC_ALL", "Korean")

aerosol_data <- read.csv('C:/Users/dr2mer05/Desktop/2022RnE/aerosol_2020_1.csv')
ratio_data <- read.csv('C:/Users/dr2mer05/Desktop/2022RnE/ratio.csv')

cor(aerosol_data$평균.TSC450.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.TSC550.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.TSC700.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.BSC450.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.BSC550.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.BSC700.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC370.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC470.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC520.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC590.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC660.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC880.nm.M.m., ratio_data$ratio, method="pearson")
cor(aerosol_data$평균.AC950.nm.M.m., ratio_data$ratio, method="pearson")
