Sys.getlocale()
Sys.setlocale("LC_ALL", "C")
Sys.setlocale("LC_ALL", "Korean")

aerosol_data2 <- read.csv('C:/Users/dr2mer05/Desktop/2022RnE/aerosol_2019_12_2020_1.csv')
ratio_data2 <- read.csv('C:/Users/dr2mer05/Desktop/2022RnE/ratio2.csv')

cor(aerosol_data2$질량농도....., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$불산이온.F......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$염소이온.Cl......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$질산이온.NO3......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$나트륨이온.Na......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$암모니아이온.NH4......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$칼륨이온.K......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$마그네슘이온.Mg2......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$비해염황산이온.nss.SO42......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$비해염칼슘이온.nss.Ca2......., ratio_data2$ratio, method="pearson")
cor(aerosol_data2$황.S......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$알루미늄.Al......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$칼륨.K......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$칼슘.Ca......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$마그네슘.Mg......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$나트륨.Na......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$철.Fe......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$아연.Zn......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$바나듐.V......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$크롬.Cr......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$구리.Cu......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$망간.Mn......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$니켈.Ni......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$타이타늄.Ti......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$바륨.Ba......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$카드뮴.Cd......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$몰리브데넘.Mo......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$납.Pb......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$스트론튬.Sr......, ratio_data2$ratio, method="pearson")
cor(aerosol_data2$코발트.Co......, ratio_data2$ratio, method="pearson")
